
services:
  web3_scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7676:7676"
    environment:
      - NODE_ENV=production
      - PG_URI=postgresql://postgres:password@postgres_db:65432/cointracker
      - ALCHEMY_KEY=--
    depends_on:
      - postgres_db
    command: "pnpm start"

  postgres_db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cointracker
    ports:
      - "65432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: